disabled = false
languageCode = "pt-pt"
languageName = "Português (Portugal)"
weight = 1
title = "CV Ricardo Almeida"

[params]
  displayName = "Português (Portugal)"
  isoCode = "pt-pt"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "/img/author.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  description = "CV Ricardo Almeida"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
  name = "Ricardo Almeida"
  email = "ricardo.almeida.mail@gmail.com"
  image = "/img/author.jpg"
  imageQuality = 96
  headline = ""
  bio = "Técnico Eletrónica / Técnico Informática"
  links = [
     { email = "mailto:ricardo.almeida.mail@gmail.com" },
#     { link = "https://link-to-some-website.com/" },   
     { linkedin = "https://pt.linkedin.com/in/ricardo-almeida-0111b847/pt" }
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { facebook = "https://facebook.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { instagram = "https://instagram.com/username" },
#
   ]
