disabled = false
languageCode = "fr"
languageName = "Français"
weight = 3
title = "CV Ricardo Almeida"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "/img/author.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  description = "CV Ricardo Almeida"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
  name = "Ricardo Almeida"
  email = "youremail@example.com"
  image = "/img/author.jpg"
  imageQuality = 96
  headline = ""
  bio = "Technicien"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
     { linkedin = "https://linkedin.com/in/ricardo-almeida-0111b847" },
#     { linkedin = "https://pt.linkedin.com/in/ricardo-almeida-0111b847/pt" },
#     { facebook = "https://facebook.com/username" },
#     { instagram = "https://instagram.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
