# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to

[[main]]
  name = "Sobre"
 pageRef = "about"
  weight = 5

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tópicos"
  weight = 20

[[main]]
  name = "file topics"
  parent = "Tópicos"
  pageRef = "topics"
  weight = 20

[[main]]
  name = "CV"
  parent = "Tópicos"
  pageRef = "samples"
  weight = 20

#[[main]]
#  name = "CV ficheiro"
#  parent = "Tópicos"
#  pre = "edit"
#  pageRef = "/"
#  weight = 20

[[main]]
  name = "timeline"
  parent = "Topics"
  pageRef = "timeline/index.pt-pt.md"
  weight = 20

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20


#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
