# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site Settings
title: Ricardo Almeida
email: ricardo.almeida.mail@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site pessoal. O meu CV, os projetos actuais, alguns posts onde poderei partilhar experiências.
  Interessado em Electrónica e Informática.
baseurl: "" 
#url: "http://localhost:4000"
url: "https://ricardomalmeida.github.io/"
github_username:  ricardomalmeida
twitter_username: Ricmalmeida

# Build Settings
sass:
  sass_dir: _sass
#include: ['_pages']

#kramdown:
#  input: GFM

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


#theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google Analytics
#google_analytics: UA-173216209-1

